export const SET_FETCHING_STATUS = 'SET_FETCHING_STATUS';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const FETCH_LOCAL_DATA = 'FETCH_LOCAL_DATA';
export const SAVE_PLANETS_DATA = 'SAVE_PLANETS_DATA';
export const SET_PAGINATION = 'SET_PAGINATION';
